version : '3'
networks:
  # network to keep postgres database isolated
  dbnetwork:
services:
  node:
    image: esgfhub/esgf-node:1.2
  # ESGF postgres database
  esgf-postgres:
     image: esgfhub/esgf-postgres:1.2
     expose:
       - "5432"
     ports:
       - "5432:5432"
     container_name: postgres
     networks:
       - dbnetwork
     depends_on:
       - node
     volumes:
       - pg_data:/var/lib/pgsql/data
  install:
    build: .
    depends_on:
      - esgf-postgres
volumes:
  # postgres data and configuration
  pg_data: {}
