#Paths
ESGINI: /esg/config/esgcet/esg.ini
LD_LIBRARY_PATH: /usr/local/conda/envs/esgf-pub/lib/:/usr/local/conda/envs/esgf-pub/lib/python2.7/:/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/mod_wsgi/server
PATH: /usr/local/openssl/bin:/usr/local/java/bin:/usr/local/tomcat/bin:/usr/local/globus/bin:/usr/local/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/anaconda2/bin
myLD_LIBRARY_PATH: /usr/local/openssl/lib:/usr/local/globus/lib:/usr/local/geoip/lib:/usr/lib64:/usr/lib
myPATH: /usr/local/openssl/bin:/usr/local/java/bin:/usr/local/tomcat/bin:/usr/local/globus/bin:/usr/local/bin:/sbin:/usr/bin:/usr/sbin

ENV_VARIABLES:
  - GIT_SSL_NO_VERIFY: "1"
  - OPENSSL_HOME : openssl_install_dir
  - PGHOME : postgress_install_dir
  - PGBINDIR : postgress_bin_dir
  - PGLIBDIR : postgress_lib_dir
  - PGUSER : postgress_user
  - PGHOST : postgress_host
  - PGPORT : postgress_port
  - CDAT_HOME : cdat_home
  - JAVA_HOME : java_install_dir
  - JAVA_OPTS : java_opts
  - ANT_HOME : ant_install_dir
  - CATALINA_HOME : tomcat_install_dir
  - CATALINA_BASE : CATALINA_HOME
  - CATALINA_OPTS : tomcat_opts
  - GLOBUS_LOCATION : globus_location

#Component version numbers
cmor_version: 3.3.2
esg_orp_version: 2.9.10
esg_search_version: 4.15.8
esgcet_version: 3.5.0
esgf_dashboard_version: 1.5.19
esgf_desktop_version: 0.0.22
esgf_idp_version: 2.7.14
esgf_node_manager_db_version: 0.1.5
esgf_node_manager_version: 1.0.1
esgf_dashboard_db_version: 0.0.2
esgf_security_db_version: 0.1.5
esgf_security_version: 2.7.18
esgf_stats_api_version: 1.0.5
esgprep_version: 2.8.1
java_version: 1.8.0_162
postgress_min_version: 8.4.20
postgress_version: 8.4.20
tds_min_version: 5.0.2
tds_version: 5.0.2
tomcat_version: 8.5.9
tomcat_major_version: '8'
tomcat_min_version: 8.5.9
publisher_tag: v3.5.0
python_version: '2.7'

#Postgres constants
pg_secret_file: /esg/config/.esg_pg_pass
pg_sys_acct: postgres
pg_sys_acct_group: postgres
postgress_bin_dir: /usr/bin
postgress_driver: org.postgresql.Driver
postgress_host: localhost
postgress_install_dir: /var/lib/pgsql
postgress_jar: postgresql-8.4-703.jdbc3.jar
postgress_lib_dir: /usr/lib64/pgsql
postgress_port: '5432'
postgress_protocol: 'jdbc:postgresql:'
postgress_user: dbsuper
db_database: esgcet

#Tomcat constants
tomcat_conf_dir: /esg/config/tomcat
tomcat_dist_url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz
tomcat_group: tomcat
tomcat_http_path: http://archive.apache.org/dist/tomcat/tomcat
tomcat_install_dir: /usr/local/tomcat
tomcat_opts: ''
tomcat_pid_file: /var/run/tomcat-jsvc.pid
tomcat_user: tomcat
tomcat_users_file: /esg/config/tomcat/tomcat-users.xml

#ESG directory paths
esg_backup_dir: /esg/backups
esg_config_dir: /esg/config
esg_etc_dir: /esg/etc
esg_log_dir: /esg/log
esg_root_dir: /esg
esg_tools_dir: /esg/tools
workdir: /usr/local/src/esgf/workbench/esg
install_prefix: /usr/local
installer_home: /usr/local/src/esgf
esgf_dashboard_ip_workdir: /usr/local/src/esgf/workbench/esg/esgf-dashboard-ip
scripts_dir: /usr/local/bin

#Config file paths
esg_config_type_file: /esg/config/config_type
property_file: /esg/config/esgf.properties
install_manifest: /esg/esgf-install-manifest
envfile: /etc/esg.env

#Publisher constants
esgcet_egg_file: esgcet-3.5.0-py2.7.egg
pub_secret_file: /esg/config/.esg_pg_publisher_pass
publisher_config: esg.ini
publisher_home: /esg/config/esgcet
node_db_name: esgcet

#Java constants
java_install_dir: /usr/local/java
java_opts: ''

#Globus constants
globus_global_certs_dir: /etc/grid-security/certificates
globus_location: /usr/local/globus
no_globus: false

#Keystore constants
keystore_alias: my_esgf_node
keystore_file: /esg/config/tomcat/keystore-tomcat
ks_secret_file: /esg/config/.esg_keystore_pass

#Truststore constants
truststore_file: /esg/config/tomcat/esg-truststore.ts
truststore_password: changeit

#Miscellaneous
esgf_secret_file: /esg/config/.esgf_pass
force_install: false
thredds_content_dir: /esg/content
esgf_config_repo: "https://raw.githubusercontent.com/ESGF/esgf-config/master/esgf-prod"
