#! /bin/bash

#--------------
#User Defined / Settable (public)
#--------------
_t=${0%.*}
install_prefix=${install_prefix:-${ESGF_INSTALL_PREFIX:-"/usr/local"}}
esg_root_dir=${esg_root_dir:-${ESGF_HOME:-"/esg"}}
esg_config_dir=${esg_root_dir}/config
esg_config_type_file=${esg_config_dir}/config_type
esgf_secret_file=${esg_config_dir}/.esgf_pass
pg_secret_file=${esg_config_dir}/.esg_pg_pass
pub_secret_file=${esg_config_dir}/.esg_pg_publisher_pass
ks_secret_file=${esg_config_dir}/.esg_keystore_pass
install_manifest=${install_manifest:-"${esg_root_dir}/esgf-install-manifest"}
install_logfile=${install_manifest}
logfile=${logfile:-"/tmp/${_t##*/}.out"}
#--------------


init() {
    #--------------------------------
    # Internal esgf node code versions 
    #--------------------------------

    cdat_version=${cdat_version:-"1.5.0"}
    cdat_tag="1.5.1.esgf-v1.7.0"
    esgcet_version=${esgcet_version:-"2.12.3"}
    publisher_tag=${publisher_tag:-"v2.12.3"}

    #see esgf-node-manager project:
    esgf_node_manager_version=${esgf_node_manager_version:-"0.7.1"}
    esgf_node_manager_db_version=${esgf_node_manager_db_version:-"0.1.5"}

    #see esgf-security project:
    esgf_security_version=${esgf_security_version:-"2.5.2"}
    esgf_security_db_version=${esgf_security_db_version:-"0.1.5"}

    #see esg-orp project:
    esg_orp_version=${esg_orp_version:-"2.4.2"}

    #see esgf-idp project:
    esgf_idp_version=${esgf_idp_version:-"2.4.7"}

    #see esg-search project:
    esg_search_version=${esg_search_version:-"3.9.3"}

    #see esgf-web-fe project:
    esgf_web_fe_version=${esgf_web_fe_version:-"2.6.0"}

    #see esgf-dashboard project:
    esgf_dashboard_version=${esgf_dashboard_version:-"1.3.9"}
    esgf_dashboard_db_version=${esgf_dashboard_db_version:-"0.0.1"}

    #see esgf-desktop project:
    esgf_desktop_version=${esgf_desktop_version:-"0.0.7"}

    #--------------------------------
    # External programs' versions
    #--------------------------------
    openssl_version=${openssl_version:="0.9.8r"} ; openssl_min_version=${openssl_min_version:="0.9.8e"} ; openssl_max_version=${openssl_max_version:="0.9.9z"}
    java_version=${java_version:-"1.7.0_21"} ; java_min_version=${java_min_version:-"1.7.0_21"}
    ant_version=${ant_version:-"1.9.1"} ; ant_
