version: 2

aliases:
   - &install_miniconda
     name: install_miniconda
     command: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
        bash ./miniconda3.sh -b -p $WORKDIR/miniconda3
        export PATH=$WORKDIR/miniconda3/bin:$PATH
        conda install pip
        pip install flake8
        
   - &run_tests
     name: run_tests
     command: |
        export PATH=$WORKDIR/miniconda3/bin:$PATH
        python tests/test_flake8.py
     no_output_timeout: 30m
        
jobs:
   centos_build:
      docker:
         - image: muryanto1/centos_for_esgf_installer_root:latest
      working_directory: workspace
      environment:
         WORKDIR: /workspace/workdir
      steps:
         - checkout
         - run: *install_miniconda
         - run: *run_tests

workflows:
   version: 2
   esgf_installer:
      jobs:
         - centos_build
