version: 2

aliases:
   - &install_miniconda
     name: install_miniconda
     command: |
        pwd
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
        bash ./miniconda3.sh -b -p miniconda3
        pwd
        ls
        
   - &run_tests
     name: run_tests
     command: |
        #source /usr/local/conda/bin/activate esgf-pub
        #/usr/local/conda/bin/conda install flake8
        #/usr/local/conda/bin/python tests/test_flake8.py
        #source /usr/local/conda/bin/deactivate

jobs:
   centos_build:
      docker:
         # - image: hill119/esgf_centos6
         #- image: muryanto1/mycentos:latest
         - image: muryanto1/centos_for_esgf_installer_root:latest
      working_directory: workspace
      steps:
         - checkout
         - install_miniconda
         #- run: *run_tests

workflows:
   version: 2
   esgf_installer:
      jobs:
         - centos_build
