version: 2

aliases:
   - &create_esgf_pub_env
     name: create_esgf_pub_env
     command: |
        git status
        chmod 777 esg_bootstrap.sh
        ./esg_bootstrap.sh

   - &run_tests
     name: run_tests
     command: |
        source /usr/local/conda/bin/activate esgf-pub
        python tests/test_cog.py
        python tests/test_dashboard.py
        python tests/test_esg_cert_manager.py
        python tests/test_env_writer.py
        source /usr/local/conda/bin/deactivate

jobs:
   centos_build:
      docker:
         # - image: hill119/esgf_centos6
         #- image: muryanto1/mycentos:latest
         - image: muryanto1/centos_for_esgf_installer_root:latest
      working_directory: workspace
      steps:
         - checkout
         - run: *create_esgf_pub_env
         - run: *run_tests

workflows:
   version: 2
   esgf_installer:
      jobs:
         - centos_build
