#!/bin/bash

#==== SITE SPECIFIC PARAMETERS - CHANGE AS NEEDED =====

# Source ESGF environment variables file
ESGF_ENVFILE=/etc/esg.env
if [ -e "$ESGF_ENVFILE" ]; then
  source $ESGF_ENVFILE
fi
LD_LIBRARY_PATH=/opt/esgf/python/lib:$LD_LIBRARY_PATH
# ESGF_INSTALL_PREFIX
ESGF_INSTALL_PREFIX=${ESGF_INSTALL_PREFIX:-"/usr/local"}

# CoG software root directory
COG_DIR=${COG_DIR:-${ESGF_INSTALL_PREFIX}/cog}

# true if CoG is installed on ESGF node
ESGF=true

# the user and group running the CoG application
USER=apache
GROUP=apache

# the specific CoG branch OR version to install
# ESGF version
VERSION=v2.14.0

# COG_TAG=master
COG_TAG=$VERSION

# must start from bare-bone Python 2.7.9 installation that contains only setup_tools, pip and virtualenv
PATH=/opt/esgf/python/bin:$PATH

# location to unpack the Python eggs - must be writable by $USER
PYTHON_EGG_CACHE_DIR=/var/www/.python-eggs

#=== ESGF INSTALLATION LOGIC - DO NOT CHANGE =========

# Sourcing ESGF Functions
ESG_FUNCTIONS_FILE=$ESGF_INSTALL_PREFIX/bin/esg-functions
source $ESG_FUNCTIONS_FILE

# ESGF installation path
INSTALLPATH=$COG_DIR

# ESGF common installation script
INSTALLARG_SCRIPT=$ESGF_INSTALL_PREFIX/bin/esg-installarg
if [ -e "$INSTALLARG_SCRIPT" ]; then
  source $INSTALLARG_SCRIPT
fi

#=== CoG INSTALLATION LOGIC - DO NOT CHANGE ==========

# pre-requisites
pip install virtualenv

# root directory for installation
mkdir -p $INSTALLPATH

# directory for local settings
export COG_CONFIG_DIR=$INSTALLPATH/cog_config
mkdir -p $COG_CONFIG_DIR

# installation directory
# will be created during git checkout
COG_INSTALL_DIR=$INSTALLPATH/cog_install

# use Python virtual environment
cd $INSTALLPATH
virtualenv -p /opt/esgf/python/bin/python2.7 venv
source venv/bin/activate
echo 'Using Python:' `which python`

# initial checkout CoG software stack
cd $INSTALLPATH
if [ ! -d "$COG_INSTALL_DIR" ]; then
  git clone https://github.com/EarthSystemCoG/COG cog_install
fi

# checkout a specific tag or version
cd $COG_INSTALL_DIR
git pull
git checkout $COG_TAG
if [ $? != 0 ]; then
  echo "Unknown COG_TAG: $COG_TAG"
  exit 1
fi
git pull

# install CoG dependencies within Python virtual environment
cd $COG_INSTALL_DIR
python setup.py install

# create or upgrade CoG installation
python setup.py setup_cog --esgf=$ESGF

# FIXME: must download and install Globus Nexus manually
cd $COG_DIR
git clone https://github.com/globusonline/python-nexus-client.git
cd python-nexus-client/
python setup.py install

# cleanup CoG egg
cd $INSTALLPATH
rm -rf venv/lib/python2.7/site-packages/cog*

# change ownership of COG_CONFIG_DIR/site_media
chown -R $USER:$GROUP $COG_CONFIG_DIR
chown -R $USER:$GROUP $COG_INSTALL_DIR

# create location where Python eggs can be unpacked by user 'apache'
mkdir -p $PYTHON_EGG_CACHE_DIR
chown -R $USER:$GROUP $PYTHON_EGG_CACHE_DIR

# Copying installation script in installation directory
rm -f $INSTALLPATH/$0
cp $0 $INSTALLPATH

# Write CoG environment variable
echo "export COG_DIR=$INSTALLPATH" >> $ESGF_ENVFILE
echo "export COG_INSTALL_DIR=$INSTALLPATH/cog_install" >> $ESGF_ENVFILE
echo "export COG_CONFIG_DIR=$INSTALLPATH/cog_config" >> $ESGF_ENVFILE
echo "export SSL_CERT_DIR=/etc/grid-security/certificates" >> $ESGF_ENVFILE
echo "export PYTHON_EGG_CACHE=$PYTHON_EGG_CACHE_DIR" >> $ESGF_ENVFILE
dedup $ESGF_ENVFILE && source $ESGF_ENVFILE
