#!/bin/bash

#####
# deploy-compute-stack: Deploy script for ESGF Node Compute Stack 
#
#****************************************************************************
#*                                                                          *
#*    Organization: Lawrence Livermore National Lab (LLNL)                  *
#*    Directorate: Computation                                              *
#*    Department: Computing Applications and Research                       *
#*    Division: S&T Global Security                                         *
#*    Matrix: Atmospheric, Earth and Energy Division                        *
#*    Program: PCMDI                                                        *
#*    Project: Earth Systems Grid Fed (ESGF) Node Software Stack            *
#*    First Author: Eugenia Gabrielova (gabrielov1@llnl.gov)                *
#*                                                                          *
#****************************************************************************
#*                                                                          *
#*   Copyright (c) 2009, Lawrence Livermore National Security, LLC.         *
#*   Produced at the Lawrence Livermore National Laboratory                 *
#*   Written by: Gavin M. Bell (gavin@llnl.gov)                             *
#*               Eugenia Gabrielova (gabrielov1@llnl.gov)                   *
#*   LLNL-CODE-420962                                                       *
#*                                                                          *
#*   All rights reserved. This file is part of the:                         *
#*   Earth System Grid Fed (ESGF) Node Software Stack, Version 1.0          *
#*                                                                          *
#*   For details, see http://esgf.org/                                      *
#*   Please also read this link                                             *
#*    http://esgf.org/LICENSE                                               *
#*                                                                          *
#*   * Redistribution and use in source and binary forms, with or           *
#*   without modification, are permitted provided that the following        *
#*   conditions are met:                                                    *
#*                                                                          *
#*   * Redistributions of source code must retain the above copyright       *
#*   notice, this list of conditions and the disclaimer below.              *
#*                                                                          *
#*   * Redistributions in binary form must reproduce the above copyright    *
#*   notice, this list of conditions and the disclaimer (as noted below)    *
#*   in the documentation and/or other materials provided with the          *
#*   distribution.                                                          *
#*                                                                          *
#*   Neither the name of the LLNS/LLNL nor the names of its contributors    *
#*   may be used to endorse or promote products derived from this           *
#*   software without specific prior written permission.                    *
#*                                                                          *
#*   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS    *
#*   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT      *
#*   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS      *
#*   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE    *
#*   LIVERMORE NATIONAL SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR     *
#*   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,           *
#*   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT       *
#*   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF       *
#*   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND    *
#*   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,     *
#*   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT     *
#*   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF     *
#*   SUCH DAMAGE.                                                           *
#*                                                                          *
#****************************************************************************
#####

#####
# Description: Deploy Script for ESG Compute Stack
# Authors: Eugenia Gabrielova <genia.likes.science@gmail.com>
#####

# Internal Variables
preview_mode=0

# Source ESG-Compute-Tools
envfile=/etc/esg.env
esg_functions_file=esg-functions
compute_tools_file=esg-compute-tools

[ -e ${envfile} ] && source ${envfile} && ((VERBOSE)) && printf "sourcing environment from: ${envfile} \n"
[ -e ${esg_functions_file} ] && source ${esg_functions_file} && ((VERBOSE)) && printf "sourcing from: ${esg_functions_file} \n"
[ -e ${compute_tools_file} ] && source ${compute_tools_file} && ((VERBOSE)) && printf "sourcing from: ${compute_tools_file} \n"
# DEBUG
source ../esg-functions

########################
# Compute Stack        #
########################

deploy_local_standalone_stack() {
    run_monit
    run_mesos_start_master --port=$mesos_master_port
    local standaloneMesosMasterURL=$(get_config_ip eth0):$mesos_master_port
    run_mesos_start_slave $standaloneMesosMasterURL
}

deploy_local_replicated_stack() {
    run_monit
    run_zookeeper_start_local_replicated_servers
    run_mesos_start_local_replicated_masters
    run_mesos_start_slave file://$zookeeper_replicated_master_url_file
}

deploy_cluster_stack() {
    echo "Under construction D: So lonely..."
}

deploy_compute_tools() {

    echo "Deploying ESG Compute Stack..."
    echo
    echo "Please select a distribution level for the compute stack: "
    echo "  [1] Standalone -    No replication. Good for basic debugging.
                        Single instances of Mesos, monitoring with Monit
                        Run jobs locally with Spark, Hadoop, MPI"
    echo "  [2] Local Cluster - Local replication. Good for small-scale distribution.
                        Multiple local Mesos Master nodes, managed with Zookeeper. 
                        Run jobs locally with Spark, Hadoop, MPI.
                        Monitoring with Monit."
    echo "  [3] Cluster -       Replicate stack on multiple machines. Production mode.
                        Node quorum management with Zookeeper.
                        Run jobs on Spark, Hadoop, MPI on cluster.
                        Monitoring with Monit."
    echo -n "Please select a mode [default = 1]: " 
    read stackClusterLevel

    if [ ! $stackClusterLevel ]; then
        # If there is no argument, we default to 1: Local Standalone"
        deploy_local_standalone_stack

    elif [ $stackClusterLevel == 1 ]; then
        deploy_local_standalone_stack

    elif [ $stackClusterLevel == 2 ]; then
        deploy_local_replicated_stack

    elif [ $stackClusterLevel == 3 ]; then
        deploy_cluster_stack
    else
        echo "Invalid selection. Please run deploy script again."
        return 1
    fi
}

########################
# Deploy Options       #
########################
activate_preview_mode() {
    echo "Activating Preview Mode..."
    local hasLynx=$(which lynx >& /dev/null)
    if [ $hasLynx ] && [ $hasLynx == 0 ]; then
        echo "Preview Mode: On"
        preview_mode=1
    else
        echo "Activation failed: Missing Lynx"
        echo "To start compute stack in Preview Mode, "
        echo "please install Lynx (http://lynx.isc.org/)."
        echo
    fi
}   

show_help_menu() {
    echo
    echo "--help [-h]           Display this help menu."
    echo "--preview-mode [-p]   Run with previews of monitoring for stack tools."
    echo
}

if [[ "$BASH_SOURCE" == "$0" ]]
then
    # Placeholder: Sanity checks

    if [ $1 ]; then 
        if [ $1 = '--preview-mode' ] || [ $1 = '-p' ]; then 
            activate_preview_mode 
        fi
        if [ $1 = '--help' ] || [ $1 == '-h' ]; then
            show_help_menu
            exit
        fi
    fi   
    deploy_compute_tools   
fi
