#!/bin/bash

#####
# esg-node: ESGF Node Application Stack - Compute Tools
# description: Compute tools installer for the ESGF Node application stack
#
#****************************************************************************
#*                                                                          *
#*    Organization: Lawrence Livermore National Lab (LLNL)                  *
#*    Directorate: Computation                                              *
#*    Department: Computing Applications and Research                       *
#*    Division: S&T Global Security                                         *
#*    Matrix: Atmospheric, Earth and Energy Division                        *
#*    Program: PCMDI                                                        *
#*    Project: Earth Systems Grid Fed (ESGF) Node Software Stack            *
#*    First Author: Eugenia Gabrielova (gabrielov1@llnl.gov)                *
#*                                                                          *
#****************************************************************************
#*                                                                          *
#*   Copyright (c) 2009, Lawrence Livermore National Security, LLC.         *
#*   Produced at the Lawrence Livermore National Laboratory                 *
#*   Written by: Gavin M. Bell (gavin@llnl.gov)                             *
#*   LLNL-CODE-420962                                                       *
#*                                                                          *
#*   All rights reserved. This file is part of the:                         *
#*   Earth System Grid Fed (ESGF) Node Software Stack, Version 1.0          *
#*                                                                          *
#*   For details, see http://esgf.org/                                      *
#*   Please also read this link                                             *
#*    http://esgf.org/LICENSE                                               *
#*                                                                          *
#*   * Redistribution and use in source and binary forms, with or           *
#*   without modification, are permitted provided that the following        *
#*   conditions are met:                                                    *
#*                                                                          *
#*   * Redistributions of source code must retain the above copyright       *
#*   notice, this list of conditions and the disclaimer below.              *
#*                                                                          *
#*   * Redistributions in binary form must reproduce the above copyright    *
#*   notice, this list of conditions and the disclaimer (as noted below)    *
#*   in the documentation and/or other materials provided with the          *
#*   distribution.                                                          *
#*                                                                          *
#*   Neither the name of the LLNS/LLNL nor the names of its contributors    *
#*   may be used to endorse or promote products derived from this           *
#*   software without specific prior written permission.                    *
#*                                                                          *
#*   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS    *
#*   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT      *
#*   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS      *
#*   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE    *
#*   LIVERMORE NATIONAL SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR     *
#*   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,           *
#*   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT       *
#*   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF       *
#*   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND    *
#*   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,     *
#*   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT     *
#*   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF     *
#*   SUCH DAMAGE.                                                           *
#*                                                                          *
#****************************************************************************
#####

#####
# Description: Installer for ESG Compute Tools
# Authors: gabrielov1@llnl.gov
####

#####
# uses: git, tar
#####

#--------------
# User Defined / Settable (public)
#--------------
install_prefix=${install_prefix:-"/usr/local"}
DEBUG=${DEBUG:-0}
git_placeholder="$install_prefix/git"
git_exec_path_param="--exec-path=$git_placeholder/libexec/git-core"
java_placeholder="$install_prefix/java"
java_install_path_config_param="--with-java-home=$java_placeholder/bin/java"
compress_extensions=".tar.gz|.tar.bz2|.tgz|.bz2|.tar"

#--------------------------------
# External programs' versions
#--------------------------------
mesos_version=${mesos_version:="0.9.0"}
mesos_min_version=${mesos_min_version:="0.9.0"}
scala_version=${scala_version:="2.9.2"}
scala_min_version=${scala_min_version:="2.9.1"}

#--------------------------------
# External programs' script variables
#--------------------------------
mesos_install_dir=${MESOS_HOME:-${install_prefix}/mesos}
mesos_git_url="git://git.apache.org/mesos.git"
scala_install_dir=${SCALA_HOME:-${install_prefix}/scala}
scala_dist_url="http://www.scala-lang.org/downloads/distrib/files/scala-2.9.2.tgz"

#####
# Mesos (Cluster manager for resource sharing across distirbuted applications)
#####

# Fixme find uninstall template
uninstall_mesos () {
	if [ -d "$mesos_install_dir" ]; then
		sudo rm -r "$mesos_install_dir"
	fi
}

# FIXME Look up esg-node test formatting
test_mesos_build () {
	cd "$mesos_install_dir"
	#make check
	echo
	echo "---------------"
	echo "Skipping Mesos Test Temporarily"
	echo "---------------"
	echo
}

# Mesos is an Apache project, and can be obtained from its git and svn repositories. 
# For the purpose of this installation, we use the git repository as the source, and 
# configure the mesos install with local versions of java and git.
get_mesos () {
	if [! -d $mesos_install_dir ]
	then
		git "$git_exec_path_param" clone "$mesos_git_url" "$mesos_install_dir"
	else
		cd "$mesos_install_dir"
		make clean
	fi

	cd "$mesos_install_dir"
	./bootstrap
	./configure "$java_install_path_config_param" --with-webui --with-included-zookeeper
	make
	test_mesos_build
}

compute_setup_mesos() {
	echo -n "[Placeholder] Checking for mesos >= ${mesos_min_version}"
 	#check_version mesos ${mesos_min_version}
 	#[ $? == 0 ] && (( ! force_install )) && echo " [OK]" && return 0
 
	echo
	echo "*******************************"
 	echo "Setting up Mesos ${mesos_version}"
 	echo "*******************************"
	echo

	# Get Mesos from Online Source
	get_mesos
}

#####
# Scala (FIXME describe Scala in a manner relevant to ESG here)
#####

uninstall_scala () {
	if [ -e ${scala_install_dir} ]; then
		sudo rm -r ${scala_install_dir}
	fi
}

get_scala() {
	# Debug Placeholder
	uninstall_scala
	
	# Retrieve Scala
	local scala_dist_file=${scala_dist_url##*/}
	# strip off .tar.gz at the end
	local scala_dist_dir=$(echo ${scala_dist_file} | awk 'gsub(/('$compress_extensions')/,"")')

	if [ ! -e ${scala_install_dir} ]; then
		echo "Don't see Scala distribution directory ${scala_dist_dir}"
		if [ ! -e "${install_prefix}/${scala_dist_file}" ]; then
			echo "Don't see Scala distribution file ${scala_dist_file} either"
			echo "Downloading Scala from ${scala_dist_url}"
			wget -O ${scala_dist_file} ${scala_dist_url}
			#[ $? != 0 ] && echo " ERROR: Could not download Scala:${scala_dist_file}" && popd && checked_done 1
			echo "Unpacking ${scala_dist_file}..."
			tar xzf ${scala_dist_file} -C "${install_prefix}/"
			mv "${install_prefix}/${scala_dist_dir}" ${scala_install_dir}
			#[ $? != 0 ] && echo " ERROR: Could not extract OpenSSL: ${openssl_dist_file}" && popd && checked_done 1
		fi
	fi

	# If directory does not exist but distribution archive does, unpack and continue
	if [ -e "${install_prefix}/${scala_dist_file}" ] && [ ! -e ${scala_install_dir} ]; then
		echo "unpacking ${scala_dist_file}..."
 		tar xzf ${scala_dist_file} -C "${install_prefix}/"
		mv "${install_prefix}/${scala_dist_dir}" ${scala_install_dir}
	fi

	# The Scala distribution we are obtaining contains scala as an executable in its bin/
	# subdirectory. No further action is needed if the file is unpacked correctly, though
	# some error-checking will be added here in case there are other issues.
	if [ -e ${scala_dist_file} ]; then
		rm ${scala_dist_file}
	fi
}

compute_setup_scala() {
	echo -n "Checking for scala >= ${scala_min_version}"
	#check_version scala ${scala_min_version}
	#[ $? == 0 ] && (( ! force_install )) && echo " [OK]" && return 0

	echo
	echo "*****************************"
	echo "Setting up Scala ${scala_version}"
	echo "*****************************"
	echo

	# Set up Scala
	get_scala
}

#####
# Spark (FIXME ESG-relevant Spark description here)
#####
compute_setup_spark() {
	echo
}

#####
# Hadoop (FIXME ESG-relevant Hadoop description here)
#####
compute_setup_hadoop() {
	echo
}

#####
# Core Methods
#####

# Uninstall Mesos, Spark, Scala, Hadoop
uninstall_compute_tools() {
	uninstall_scala
	# uninstall_spark
	# uninstall_hadoop
	uninstall_mesos
}

setup_compute_tools() {
	echo
	echo "-----------------------------------"
	echo "ESGF Node Compute Tools"
	echo "-----------------------------------"
	echo

	# Installing Scala
	compute_setup_scala

	# Installing Spark
	compute_setup_spark

	# Installing Hadoop
	compute_setup_hadoop

	# Installing Mesos
	# compute_setup_mesos
}

if [[ "$BASH_SOURCE" == "$0" ]]
then
	echo
	echo "----- Setting Up Compute Tools -----"
	setup_compute_tools
fi
