#!/bin/bash

#####
# esg-compute-languages: ESGF Node Application Stack - Compute Languages
# description: Computation languages installer for the ESGF Node application 
# stack
#
#****************************************************************************
#*                                                                          *
#*    Organization: Lawrence Livermore National Lab (LLNL)                  *
#*    Directorate: Computation                                              *
#*    Department: Computing Applications and Research                       *
#*    Division: S&T Global Security                                         *
#*    Matrix: Atmospheric, Earth and Energy Division                        *
#*    Program: PCMDI                                                        *
#*    Project: Earth Systems Grid Fed (ESGF) Node Software Stack            *
#*    First Author: Eugenia Gabrielova (gabrielov1@llnl.gov)                *
#*                                                                          *
#****************************************************************************
#*                                                                          *
#*   Copyright (c) 2009, Lawrence Livermore National Security, LLC.         *
#*   Produced at the Lawrence Livermore National Laboratory                 *
#*   Written by: Gavin M. Bell (gavin@llnl.gov)                             *
#*               Eugenia Gabrielova (gabrielov1@llnl.gov)                   *
#*   LLNL-CODE-420962                                                       *
#*                                                                          *
#*   All rights reserved. This file is part of the:                         *
#*   Earth System Grid Fed (ESGF) Node Software Stack, Version 1.0          *
#*                                                                          *
#*   For details, see http://esgf.org/                                      *
#*   Please also read this link                                             *
#*    http://esgf.org/LICENSE                                               *
#*                                                                          *
#*   * Redistribution and use in source and binary forms, with or           *
#*   without modification, are permitted provided that the following        *
#*   conditions are met:                                                    *
#*                                                                          *
#*   * Redistributions of source code must retain the above copyright       *
#*   notice, this list of conditions and the disclaimer below.              *
#*                                                                          *
#*   * Redistributions in binary form must reproduce the above copyright    *
#*   notice, this list of conditions and the disclaimer (as noted below)    *
#*   in the documentation and/or other materials provided with the          *
#*   distribution.                                                          *
#*                                                                          *
#*   Neither the name of the LLNS/LLNL nor the names of its contributors    *
#*   may be used to endorse or promote products derived from this           *
#*   software without specific prior written permission.                    *
#*                                                                          *
#*   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS    *
#*   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT      *
#*   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS      *
#*   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE    *
#*   LIVERMORE NATIONAL SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR     *
#*   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,           *
#*   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT       *
#*   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF       *
#*   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND    *
#*   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,     *
#*   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT     *
#*   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF     *
#*   SUCH DAMAGE.                                                           *
#*                                                                          *
#****************************************************************************
#####

#####
# Description: Installer for ESG Computation Languages
# Authors: gabrielov1@llnl.gov
#####

#####
# uses: unzip, wget 
#####

#--------------
# User Defined / Settable (public)
#--------------
install_prefix=${install_prefix:-"/usr/local"}
DEBUG=${DEBUG:-0}
VERBOSE=${VERBOSE:-0}
devel=${devel:-0}
compress_extensions=".tar.gz|.tar.bz2|.tgz|.bz2|.tar|.zip"
envfile="/etc/esg.env"

#--------------------------------
# External programs' versions
#--------------------------------
clojure_version=${clojure_version:="1.4.0"}
clojure_min_version=${clojure_min_version:="1.4.0"}
scala_version=${scala_version:="2.9.2"}
scala_min_version=${scala_min_version:="2.9.1"} # 2.9.1 is the minimum version supported by Spark.

#--------------------------------
# External programs' script variables
#--------------------------------
clojure_install_dir=${CLOJURE_HOME:-${install_prefix}/clojure}
clojure_dist_url="http://repo1.maven.org/maven2/org/clojure/clojure/${clojure_version}/clojure-${clojure_version}.zip"
scala_install_dir=${SCALA_HOME:-${install_prefix}/scala}
scala_dist_url="http://www.scala-lang.org/downloads/distrib/files/scala-${scala_version}.tgz"

export SCALA_HOME=${scala_install_dir}
export CLOJURE_HOME=${clojure_install_dir}

#####
# Clojure (a powerful dialect of Lisp that supports multicore computing on the JVM and a number
# of other powerful computing facilities)
#####

uninstall_clojure() {
    # Delete clojure install directory
	if [ -e ${clojure_install_dir} ]; then
        sudo rm -r ${clojure_install_dir}
    fi

	# Remove clojure home from environment
	local key=${1}
	sed -i '/'${key}'/d' ${envfile}
}

get_clojure() {
	# TODO Check for empty file size in distributed file

    # Retrieve Clojure Distribution File
	local clojure_dist_file=${clojure_dist_url##*/}
	local clojure_dist_dir=$(echo ${clojure_dist_file} | awk 'gsub(/('$compress_extensions')/,"")')

	if [ ! -e ${clojure_install_dir} ]; then
		echo "Don't see Clojure distribution directory ${clojure_install_dir}"
		wget -O "${install_prefix}/${clojure_dist_file}" ${clojure_dist_url}
		#[ $? != 0 ] && echo " ERROR: Could not download Clojure: ${clojure_dist_file}" && popd && checked_done 1
		echo "Unpacking ${clojure_dist_file}..."
		unzip -q "${install_prefix}/${clojure_dist_file}" -d ${install_prefix}
		mv "${install_prefix}/${clojure_dist_dir}" ${clojure_install_dir}
		chmod 755 ${clojure_install_dir}
		#[ $? != 0 ] && echo " ERROR: Could not extract Clojure: ${clojure_dist_file}" && popd && checked_done 1

		cd ${clojure_install_dir}
		ant
	fi

	# TODO Set CLOJURE_HOME environment variable
	
	# Remove Clojure Distribution File
	if [ -e "${install_prefix}/${clojure_dist_file}" ]; then
        rm "${install_prefix}/${clojure_dist_file}"
	fi
}

compute_check_version_clojure() {
	echo `java -jar ${clojure_install_dir}/clojure.jar --eval 'println (str (get *clojure-version* :major)"."(get *clojure-version* :minor)"."(get *clojure-version* :incremental))' |xargs | awk '{print $3}'`
}

compute_setup_clojure() {
	echo
    echo "Checking for clojure >= ${clojure_min_version}"
    compute_check_version_clojure clojure ${clojure_min_version}
    #[ $? == 0 ] && (( ! force_install )) && echo " [OK]" && return 0

    echo
    echo "*****************************"
    echo "Setting up Clojure ${clojure_version}"
    echo "*****************************"
    echo

    # Set up Clojure
    get_clojure
}

#####
# Scala (both functional and object-oriented, Scala integrates well with Java and provides support
# for concurrency and scalability)
#####

uninstall_scala() {
	# Remove scala install directory
	if [ -e ${scala_install_dir} ]; then
        sudo rm -r ${scala_install_dir}
    fi

	# Remove scala home from environment
	local key=${1}
	sed -i '/'${key}'/d' ${envfile}
}

get_scala() {
	# TODO Check for empty file size

    # Retrieve Scala
    local scala_dist_file=${scala_dist_url##*/}
    # strip off .tar.gz at the end
    local scala_dist_dir=$(echo ${scala_dist_file} | awk 'gsub(/('$compress_extensions')/,"")')

    if [ ! -e ${scala_install_dir} ]; then
        echo "Don't see Scala distribution directory ${scala_dist_dir}"
        if [ ! -e "${install_prefix}/${scala_dist_file}" ]; then
            echo "Don't see Scala distribution file ${scala_dist_file} either"
            echo "Downloading Scala from ${scala_dist_url}"
            wget -O ${scala_dist_file} ${scala_dist_url}
            #[ $? != 0 ] && echo " ERROR: Could not download Scala:${scala_dist_file}" && popd && checked_done 1
            echo "Unpacking ${scala_dist_file}..."
            tar xzf ${scala_dist_file} -C "${install_prefix}/"
            mv "${install_prefix}/${scala_dist_dir}" ${scala_install_dir}
            #[ $? != 0 ] && echo " ERROR: Could not extract OpenSSL: ${openssl_dist_file}" && popd && checked_done 1
        fi
    fi

    # If directory does not exist but distribution archive does, unpack and continue
    if [ -e "${install_prefix}/${scala_dist_file}" ] && [ ! -e ${scala_install_dir} ]; then
        echo "unpacking ${scala_dist_file}..."
        tar xzf ${scala_dist_file} -C "${install_prefix}/"
        mv "${install_prefix}/${scala_dist_dir}" ${scala_install_dir}
    fi

	# TODO Set SCALA_HOME environment variable in environment and environment file
	#export SCALA_HOME="${scala_install_dir}/bin/"

    # The Scala distribution we are obtaining contains scala as an executable in its bin/
    # subdirectory. No further action is needed if the file is unpacked correctly, though
    # some error-checking will be added here in case there are other issues.
    if [ -e ${scala_dist_file} ]; then
        rm ${scala_dist_file}
    fi
}

compute_check_version_scala() {
	echo -n Scala `${SCALA_HOME}/bin/scala -version | awk '{print $5}'`
}

compute_setup_scala() {
    echo
	echo "Checking for scala >= ${scala_min_version}"
    compute_check_version_scala scala ${scala_min_version}
    #[ $? == 0 ] && (( ! force_install )) && echo " [OK]" && return 0

    echo
    echo "*****************************"
    echo "Setting up Scala ${scala_version}"
    echo "*****************************"
    echo

    # Set up Scala
    get_scala
}

#####
# Core Compute Language Methods - Call all setup methods, or uninstall all
#####

uninstall_compute_languages() {
	echo
    echo "-----------------------------------"
	echo "Uninstalling ESGF Compute Languages"
	echo "-----------------------------------"
	echo

	# Uninstalling Scala
	uninstall_scala SCALA_HOME

	# Uninstalling Clojure
	uninstall_clojure CLOJURE_HOME
}

setup_compute_languages() {
    echo
    echo "-----------------------------------"
    echo "ESGF Node Compute Languages"
    echo "-----------------------------------"
    echo

	# Install Scala
	compute_setup_scala

	# Install Clojure
	compute_setup_clojure
}

if [[ "$BASH_SOURCE" == "$0" ]]
then
    echo
    echo "----- Setting Up Compute Languages -----"
    setup_compute_languages
fi
